## Client ##
type: InterpolateClient

ce_loss:
  weight: 1 

interpolation:
  ce_weight: 1
  kl_weight: 1
  type: stochastic
  forward_type: layer
  # low: -0.5
  # high: -0.5
  branch: [l, i]
  probs: [0.33, 0.66]
  interval: [-0.5, -0.5]
  # branch_probs: [0.33, 0.66]
  branches:
    layer1:
      branch: [l, i]
      probs: [0.33, 0.66]
      interval: [-1, -1]
    layer1:
      branch: [l, i]
      probs: [0.33, 0.66]
      interval: [-0.5, -0.5]
    layer1:
      branch: [l, i]
      probs: [0.33, 0.66]
      interval: [-0.5, -0.5]
    layer1:
      branch: [l, i]
      probs: [0.33, 0.66]
      interval: [-0.5, -0.5]
    layer1:
      branch: [l, i]
      probs: [0.33, 0.66]
      interval: [-0.5, -0.5]
  repeat: 1
  temp: 1
  feature_relu: True


# interpolation:
#   type: fixed
#   factor: -0.5



# feature_align_loss:
#   weight: 1
#   align_type: cosine