## Client ##
type: InterpolateClient

ce_loss:
  weight: 1 

interpolation:
  ce_weight: 1
  kl_weight: 1
  type: stochastic
  forward_type: backbonefc
  low: -1
  high: 0
  branch: [l, g, i]
  repeat: 5
  temp: 1
  feature_relu: True


# interpolation:
#   type: fixed
#   factor: -0.5



# feature_align_loss:
#   weight: 1
#   align_type: cosine