## Client ##
type: InterpolateClient

ce_loss:
  weight: 1 

interpolation:
  ce_weight: 1
  kl_weight: 1
  type: stochastic
  low: 0
  high: 1
  branch: [l, g, i]
  repeat: 5
  temp: 1
  feature_relu: True

  # models_case: 7 # DO NOT USE INTEGER FOR BETTER READABILITY

# interpolation:
#   type: fixed
#   factor: -0.5



# feature_align_loss:
#   weight: 1
#   align_type: cosine