## Client ##
type: MetricClient

ce_loss:
  weight: 0

LC:
  weight: 1
  tau: 1
  
metric_loss:
  loss_type: supervised
  topk_pos: 1
  topk_neg: 2
  temp: 0.05
  pairs:
    - name: metric
      pos: dd
      neg: dd
      weight: 0
      loss_type: supervised
  weight: 0
  branch_level: [4]
  feature_relu: False
  # interpolation_type: full
  djr:
    use : True
    margin:
      epsilon : 0
    bal:
      sample : 1
      prob : 0
      featnorm : 0
      norm_mode : 'sqrt4' #[sum, L2]
      norm_scale_crit : 'topk_neg' #[topk_neg, num_unique_labels]
      gamma : 1

feature_align_loss:
  weight: 0
  align_type: cosine
      
