## Client ##
type: MetricClient

ce_loss:
  weight: 1
  
metric_loss:
  loss_type: supervised
  topk_pos: 1
  topk_neg: 2
  temp: 0.05
  pairs:
    - name: metric
      pos: nd
      neg: nn
      weight: 1
    # - name: metric2
    #   pos: nd
    #   neg: nd
    #   weight: 0
  weight: 1
  branch_level: [0,1,2,3,4]
  feature_relu: False
  interpolation_type: full

feature_align_loss:
  weight: 0
  align_type: cosine
