## Client ##
type: MetricInterpolateClient

ce_loss:
  weight: 1
  
metric_loss:
  loss_type: supervised
  topk_pos: 1
  topk_neg: 20
  temp: 0.05
  pairs:
    - name: metric
      pos: "no on"
      neg: "no on"
      weight: 1
    - name: metric2
      pos: "nn"
      neg: "nn"
      weight: 0
  weight: 1
  branch_level: [0,1,2,3,4]
  feature_relu: False
  interpolation_type: full

feature_align_loss:
  weight: 0
  align_type: cosine
      

interpolation:
  ce_weight: 1
  kl_weight: 1
  type: stochastic
  forward_type: layer
  low: 1
  high: 1
  branch: [l, i]
  branch_probs: [0.33, 0.66]
  repeat: 1
  temp: 1
  feature_relu: False
