## Client ##
type: MetricClient

ce_loss:
  weight: 1
  
metric_loss:
  criterion_type: subset
  loss_type: supervised
  topk_pos: 1
  topk_neg: 2
  temp: 0.05
  sampling: progress2
  sampling_ranges:
    0: 0.5
    50: 0.6
    100: 0.7
    150: 0.8
    200: 0.9
    250: 1
  pairs:
    - name: metric
      pos: nn
      neg: nn
      weight: 1
      loss_type: supervised
    - name: metric2
      pos: "nn"
      neg: "nn"
      weight: 1
      loss_type: unsupervised

  weight: 1
  branch_level: [0,1,2,3,4]
  feature_relu: False
  interpolation_type: full

feature_align_loss:
  weight: 0
  align_type: cosine
      