## Client ##
type: SimGCD_Update_Prior_Global_Client
n_views: 2
#temperature: 0.07
unsup_temperature: 1
sup_temperature: 0.07 # default
sup_con_weight: 0.35
sup_cls_weight: 0.20
unsup_con_weight: 0.65
unsup_cls_weight: 0.80
g_clipping: True

warmup_teacher_temp: 0.07
teacher_temp: 0.04
student_temp: 0.1
warmup_teacher_temp_epochs: 30
memax_weight: 7
prior_temp: 0.1
avg_temp: 0.1
distance_type: 'l2'

softmax_prior: False
label_smoothing: True
smooth_max: 0.99
shuffle_unseen_prior: False
reg_classes: 5


update_prior: True
update_prior_freq: 1
start_update: 0
update_alg: finch


align_gt: False
align_type: 'centroid'


update_lambda: 0.9


log_div_from_gt: True
soft_preds_temp: 0.04

ce_type: ce
margin_m: 0.5
margin_s: 10

# OOD-FINCH
lambda_param: 1

# estimate num clusters
est_num_clusters: False
k_mode: 's_dbw'
clust_feats: 'feats'

# Proto clustering
get_local_centroid: False
local_centroid_type: 'finch'


# Class association loss
centroids_cls_weight: 0.0


# tolerance
tolerance: 20
# alignment threshold
align_threshold: 10

## Minimum labelled samples to be considered as a valid seen cluster
min_labelled_samples: 1


# resume warmedup model
pretrained_dir: 'dino'

# stochastic freq
stochastic_freq: 1

# freeze extractor
freeze_extractor: False


# return all novel classes
return_all_novel_classes: True


lr_decay_proj_layer: 1
use_gt_prior: False


