## Client ##
type: SimGCD_GM_ENS_Client
n_views: 2
#temperature: 0.07
unsup_temperature: 1
sup_temperature: 0.07 # default
sup_con_weight: 0.35
g_clipping: False
proj_layer_lr_decay: 1
warmup_teacher_temp: 0.07
teacher_temp: 0.04
warmup_teacher_temp_epochs: 30
memax_weight: 1
ensemble_weight: 0.5