## Client ##
type: InterpolateClient

ce_loss:
  weight: 1 

label_noise:
  ratio: 0.3

interpolation:
  ce_weight: 1
  kl_weight: 1
  type: stochastic
  forward_type: layer
  low: 0
  high: 0
  branch: [l, g]
  branch_probs: [0.33, 0.66]
  repeat: 1
  temp: 1
  feature_relu: False


# interpolation:
#   type: fixed
#   factor: -0.5



# feature_align_loss:
#   weight: 1
#   align_type: cosine