## Client ##
type: MetricExtraClient_whichlearnfaster_vertical

#After 10.7 pm 7:34, delete main_celoss in extra because it already exist in the loss_metric. ce_loss weight 0.5=>1
ce_loss:
  weight: 1
  
metric_loss:
  loss_type: supervised
  topk_pos: 1
  topk_neg: 2
  temp: 0.05
  pairs:
    - name: metric
      pos: nn
      neg: nn
      weight: 1
      loss_type: supervised
    - name: metric2
      pos: "nn"
      neg: "nn"
      weight: 0
      loss_type: unsupervised
  weight: 1
  branch_level: [0,1,2,3,4]
  feature_relu: False
  interpolation_type: full

feature_align_loss:
  weight: 0
  align_type: cosine
      

interpolation:
  ce_weight: 0
  kl_weight: 0
  type: stochastic
  forward_type: layer
  low: 0
  high: 0
  branch: [l, g]
  branch_probs: [0.5, 0.5]
  repeat: 1
  temp: 1
  feature_relu: False



loc_var_sample_prototype:
  weight : 0



inverse_var_of_prototypes:
  weight : 0


diff_loc_glob_prototypes_mean:
  weight : 0



vertical:
  ce_vertical : True
  global_model_client_all_data_mean : False
  local_center_batch : False
  global_model_client_barch_data_mean: False

  global_center_momentum : -1
  local_center_momentum : -1
  modify_weight : 1
  use_local_proto : True
  use_local_feat : True



  modify_samplevar_grad : False
  modify_protovar_grad : True
  reverse_samplevar : False
  samplevar_eli : 'positive'
  direction_clipping : -1  #0.0001
