## Client ##
type: MetricExtraClient_whichlearnfaster

#After 10.7 pm 7:34, delete main_celoss in extra because it already exist in the loss_metric. ce_loss weight 0.5=>1
ce_loss:
  weight: 1
  
metric_loss:
  loss_type: supervised
  topk_pos: 1
  topk_neg: 2
  temp: 0.05
  pairs:
    - name: metric
      pos: nn
      neg: nn
      weight: 0
      loss_type: supervised
    - name: metric2
      pos: "nn"
      neg: "nn"
      weight: 0
      loss_type: unsupervised
  weight: 1
  branch_level: [4]
  feature_relu: False
  interpolation_type: full

feature_align_loss:
  weight: 0
  align_type: cosine
      

interpolation:
  ce_weight: 0
  kl_weight: 0
  type: stochastic
  forward_type: layer
  low: 0
  high: 0
  branch: [l, g]
  branch_probs: [0.5, 0.5]
  repeat: 1
  temp: 1
  feature_relu: False



loc_var_sample_prototype:
  weight : 1



inverse_var_of_prototypes:
  weight : 1


diff_loc_glob_prototypes_mean:
  weight : 1