## Trainer ##
type: Trainer
num_clients: 4
participation_rate: 0.25
# batch_size: 50
local_lr_decay: 0.998
local_lr: 0.1
local_epochs: 1
global_lr: 1.0
global_rounds: 200
client_selection:
  mode: sequential
  rounds_per_client: 100


# split.mode=skew
# split.class_per_client=50