
from clients.build import get_client_type


# from base import LocalUpdater
from clients.base_client import Client


# from clients.fedbr_client import FedBRClient
#
# from clients.metric_client_djr import MetricClient_djr
# from clients.metric_client_djr_log import MetricClient_djr_log
# from clients.metric_client_exp import MetricClient_exp
# from clients.interpolate_client import InterpolateClient, InterpolateSwitchClient
# from clients.interpolate2_client import Interpolate2Client
# from clients.metric_extra_client import MetricExtraClient
# from clients.metric_extra_client_whichlearnfaster import MetricExtraClient_whichlearnfaster
# from clients.metric_extra_client_whichlearnfaster_vertical import MetricExtraClient_whichlearnfaster_vertical
#
# from clients.extrainterpolate_client import ExtraInterpolateClient
# from clients.metric_client_dyn import MetricClient_dyn
# from clients.metric_client_mimelite import MetricClient_mimelite


from clients.GCD import GCDClient
from clients.GCD2 import GCDClient2
from clients.GCD_iterative import GCDSUIterativeClient
from clients.GCD_new import GCDClient_New

from clients.GCL import GCLClient


from clients.SimGCD import SimGCDClient
from clients.SimGCD_Global_Logit_Ens import SimGCD_GM_ENS_Client
from clients.SimGCD_feature_clutering_loss import FeatureClusteringClient

from clients.SimGCD_kl_gtprior import SimGCDGTPClient
from clients.SimGCD_ent_gtprior import SimGCD_GT_Entopy_Client
from clients.SimGCD_ent_gmprior import SimGCD_GM_Entopy_Client
from clients.SimGCD_update_prior import SimGCD_Update_Prior_Client
from clients.SimGCD_local_clustering import SimGCD_Local_Clustering_Client
from clients.SimGCD_ent_gtprior_gens import SimGCD_GT_Entopy_Ens_Client
from clients.SimGCD_update_prior_local import SimGCD_Update_Prior_Local_Client
from clients.SimGCD_update_prior_global import SimGCD_Update_Prior_Global_Client
from clients.SimGCD_update_prior_global_mask import SimGCD_Update_Prior_Global_Mask_Client
from clients.SimGCD_update_prior_global_cd import SimGCD_Update_Prior_Global_CD_Client
from clients.SimGCD_update_prior_global_OV import SimGCD_Update_Prior_Global_OV_Client

from clients.mugcd import MuGCD_Client

from clients.SimGCD_infomap_local_memory import SimGCD_Infomap_Client
from clients.SimGCD_online_prior_matching import SimGCDOnlinePriorMatchingClients
from clients.SimGCD_online_gtprior_matching import SimGCDOnlineGTPriorMatchingClients
from clients.SimGCD_online_prior_matching_semi import SimGCDOnlinePriorMatchingSemiClients
from clients.SimGCD_online_prior_matching_split import SimGCDOnlinePriorMatchingSplitClients

# from clients.GCD_hiesup import GCDClient_HieSupCon
# from clients.GCD_infomap import GCDClient_InfoMapCon
# from clients.GCD_infomap_proto import GCDClient_InfoMapCon_Proto
# from clients.GCD_infomap_seen_hard import GCDClient_InfoMapCon_SeenHard
from clients.GCD_renew import GCDClientReNew