
from clients.build import get_client_type


# from base import LocalUpdater
from clients.base_client import Client
from clients.metric_client import MetricClient, MetricInterpolateClient, \
    MetricExtrapolateUniformClient, MetricExtrapolateContrastiveClient, \
    MetricConcatenateClient, MetricExtrapolateAugmentClient


from clients.fedbr_client import FedBRClient

from clients.metric_client_djr import MetricClient_djr
from clients.metric_client_djr_log import MetricClient_djr_log
from clients.metric_client_exp import MetricClient_exp
from clients.interpolate_client import InterpolateClient, InterpolateSwitchClient
from clients.interpolate2_client import Interpolate2Client
from clients.metric_extra_client import MetricExtraClient
from clients.metric_extra_client_whichlearnfaster import MetricExtraClient_whichlearnfaster
from clients.metric_extra_client_whichlearnfaster_vertical import MetricExtraClient_whichlearnfaster_vertical

from clients.extrainterpolate_client import ExtraInterpolateClient
from clients.metric_client_dyn import MetricClient_dyn
from clients.metric_client_mimelite import MetricClient_mimelite