
#################### Default Setup ####################
wandb: True
seed: 1
enable_benchmark: True
use_amp: True
multiprocessing: False
main_gpu: '0'
num_workers: 0
pin_memory: True
verbose: False
# method_name: FedAvg
remark: ""

checkpoint_path: './checkpoints'
exp_name: base
output_model_path: 'res18.pt'
save_freq: 1000
batch_size: 50
save_test: False
eval_first: False

## Resume
load_model_path: False      # ====> may be like ./checkpoints/CIFAR100/iid/iid_base/res18.pt. use command line +load_model_path=(path)
wandb_resume_id: False

# ###### exp setting ######
# num_clients: 100
# participation_rate: 0.05
# batch_size: 50
# lr_decay: 0.998
# local_lr: 0.1
# local_epochs: 5
# global_lr: 1.0
# global_rounds: 1500 


###### wandb && logging ######
project: "FGCD"
# log_dir: '/131_data/checkpoints/bc_fl'
log_dir: './checkpoints' # 131_data

#################### Dataset ####################
# dataset:
#   name: 'CIFAR100'
#   path: './data'
#   client_path: "./client_data"
#   num_instances: 0

#################### Model ####################
model:
  name: "vit_base"
  pretrained: True
  feat_dim: 768
  mlp_out_dim: 65536
  num_mlp_layers: 3
  l2_norm: False
  training_layers: False  # or ['fc']
  grad_from_block: 11
  fft: False
  tune_normalization_layer: False
  tune_dino_head_norm: False
  num_semantics: 10
  cancel_last_layer: False


#################### Data Split ####################
split:
  mode: 'dirichlet'
  unbalanced: False
  alpha: 0.2
  overlap_ratio: 0.0
  create_client_dataset: False
  class_per_client: 0 # only for skew mode
  limit_total_classes: 3 # only for toy non_iid
  limit_number_per_class: 1000 # only for toy non_iid
  toy_noniid_rate: 0.3 # only for toy non_iid
  target_transform: True

#################### Optimizer ####################
optimizer:
  name: sgd
  momentum: 0.0
  wd: 5e-5

#################### Method ####################

# ## Server ##
# server:
#   type: Server
#   momentum : -1
#   FedACG: False


#################### Eval ####################
eval:
  freq: 1
  local_freq: 20
  retrieval_freq: 0
  batch_size: 128

analysis: True

confusion:
  freq: 0

server_umap:
  plot_locals: False
  freq: 0
  draw_classes: 10
  samples_per_class: 50
  umap_dim: 3

landscape:
  freq: 0
  resolution : 5
  x : '-1:1:5'
  y : '-1:1:5'
  xmin : -2.0
  xmax : 2.0
  xnum : 10
  ymin : -2.0
  ymax : 2.0
  ynum : 10
  adaptive_xy_range : True
  dir_type : 'states'
  ignore : None
  loss_name : CE
  adaptive_v : True
  visualize_local_loss : True
  grid_size : 1.25

visualize_prototype:
  freq: 20


compare_base_is_FedAvg : False


analysis_mode: '' # option: _flatten_feature, 




defaults:
  - _self_
  - trainer: base
  - client: base
  - evaler: base
  - dataset: cifar10
  - client_compare: base
  - server: base
  - override hydra/job_logging: colorlog_custom
  - override hydra/hydra_logging: colorlog




  # - dataset: cifar100
  # - model: ResNet18_base
