### dataset ###
name: 'imagenet'
#path: '/home2/geeho/FGCD/data'
## Enter your own data path
path: '/cvdata1/datasets/ImageNet'
client_path: "./client_data"
aug: 
- 'imagenet'
- 'imagenet'
num_instances: 0
image_size: 224
interpolation: 3
crop_pct: 0.875
download: False
seen_classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 
               10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 
               20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 
               30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 
               40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 
               ]
unseen_classes: [ 
                  50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 
               60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 
               70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
               80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 
               90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
               
test_semisup: False