## Client ##
type: MetricClient

ce_loss:
  weight: 1

prox_loss:
  weight: 0.1
  
metric_loss:
  loss_type: supervised
  topk_pos: 1
  topk_neg: 2
  temp: 0.05
  pairs:
    - name: metric
      pos: nn
      neg: nn
      weight: 0
      loss_type: supervised
  weight: 0
  branch_level: [4]
  feature_relu: False
  # interpolation_type: full

feature_align_loss:
  weight: 0.
  align_type: cosine
      